(def line (l)
     (withs (idx1 (pos #\- l)
		  idx2 (pos #\  l)
		  low  (int (cut l 0 idx1))
		  high (int (cut l (+ idx1 1) idx2))
		  cnt (count (find letter l) (list (l (+ low idx2 3)) (l (+ high idx2 3)))))
	    (is cnt 1)))

(def run-puzzle (e)
     (count t (map line (puzzle-input 2 'strs e))))
